Address requested changes:
- Trigger workflow on push
- Format sync command more cleanly
- Use GITHUB_WORKSPACE var
- Test output capturing for catching sync errors

diff --git a/.github/workflows/sync-images.yaml b/.github/workflows/sync-images.yaml
--- a/.github/workflows/sync-images.yaml
+++ b/.github/workflows/sync-images.yaml
@@ -1,7 +1,5 @@
 name: sync images
-on:
-  # TODO: Decide on triggers
-  push:
+on: push
 
 jobs:
   sync_images:
@@ -24,29 +22,40 @@ jobs:
       # - name: Setup upterm session
       #   uses: lhotari/action-upterm@v1
 
-      - name: Check component manifest for changes
-        uses: dorny/paths-filter@v2
-        id: changes
-        with:
-          filters: |
-            manifest:
-              - skopeo-manifests/${{ matrix.component }}.yml
+      # - name: Check component manifest for changes
+      #   uses: dorny/paths-filter@v2
+      #   id: changes
+      #   with:
+      #     filters: |
+      #       manifest:
+      #         - skopeo-manifests/${{ matrix.component }}.yml
 
       # NOTE: Need skopeo > v1.09 to avoid this issue:
       # https://github.com/containers/skopeo/issues/1874
       # so use containerized version
 
       - name: Sync component images
+        id: image-sync
         if: ${{ steps.changes.outputs.manifest == 'true' }}
         run: |-
           docker run --entrypoint /usr/bin/env \
-            -v /home/runner/work/azimuth-charts/azimuth-charts:/home/skopeo/azimuth-charts \
+            -v $GITHUB_WORKSPACE:/home/skopeo/azimuth-charts \
             quay.io/skopeo/stable:v1.11 \
             skopeo sync \
-            --src yaml \
-            --dest docker \
-            --dest-creds ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} \
-            --scoped \
-            --all \
-            /home/skopeo/azimuth-charts/skopeo-manifests/${{ matrix.component }}.yml \
-            ghcr.io/stackhpc/azimuth-charts
+              --src yaml \
+              --dest docker \
+              --dest-creds ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} \
+              --scoped \
+              --all \
+              /home/skopeo/azimuth-charts/skopeo-manifests/${{ matrix.component }}.yml \
+              ghcr.io/stackhpc/azimuth-charts | $GITHUB_OUTPUT
+
+      - name: Test previous step output capture
+        run: echo ${{ steps.image-sync.outputs }}
+
+      # - name: Check output for any sync errors
+      #   run: |
+      #     if [[ $(grep "level=error" ${{ steps.image-sync.outputs }} | wc -l) -gt 0 ]]; then
+      #       echo "Error messages found in output of sync"
+      #       exit 1
+      #     fi
